package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling
public class SendAndReceiveEmailApplication {

    public static void main(String[] args) {
        SpringApplication.run(SendAndReceiveEmailApplication.class, args);
//		SendMail.test();
    }

}
